Avoid compilation error due to nfsfs
Following commit is used to avoid -
ERROR: "fivm_open_verify" [fs/nfsd/nfsd.ko] undefined!
as well as removing some of the other warnings

Changelog-entry: Avoid compilation error due to nfsfs and remove some warnings
Signed-off-by: Chris Richardson <crichardson@bluechiptechnology.com>